const constants = {
    FETCH_SET_DATA : "FETCH_SET_DATA",
    FETCH_SET_MOVIE_DATA : "FETCH_SET_MOVIE_DATA",
    SET_MOVIE_DATA : "SET_MOVIE_DATA",
    SET_SEARCHTEXT : "SET_SEARCHTEXT",
    SET_SEARCHBY : "SET_SEARCHBY",
    SET_RESULTSFOUND : "SET_RESULTSFOUND",
    UPDATE_MOVIES : "UPDATE_MOVIES"
}

export default constants;